name: PMD Source Code Analyzer on Push

on: [push]

jobs:
  pmd:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup JRE
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.2'
        java-package: jre
        architecture: x64
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install

    - uses: krukmat/setup-pmd@v0.4
    - name: run-pmd
      run: pmd -d $GITHUB_WORKSPACE/force-app/main/default/classes -R category/apex/design.xml -l apex -f xml > report.xml
